package no.progark19.spacegame.utils;

import java.util.Random;

/**Created by Anders on 18.04.2018.
 * Dumb Utility class to generate dumb space-names
 * Military ranks courtesy of: ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/List_of_fictional_military_ranks.html
 * might contain some duplicates
 * */


public final class SpaceNameGenerator {
    private static final String[] RANKS = new String[] {
            "Admiral",
            "Vice Admiral",
            "Rear Admiral",
            "Captain",
            "Commander",
            "Colonel",
            "Lieutenant Colonel ",
            "Ensign",
            "Flight Sergeant",
            "Flight Corporal",
            "Senior Flight Sergeant",
            "Lieutenant",
            "Lieutenant Junior Grade",
            "Lieutenant Junior Grade",
            "Lieutenant Senior Grade",
            "Major",
            "Petty Officer",
            "Master Chief Petty Officer",
            "Chief Petty Officer",
            "Petty Officer 1st Class",
            "Petty Officer 2nd Class",
            "Specialist",
            "Private",
            "Supreme Bashar - Field Marshal",
            "Caid",
            "Burseg",
            "Bashar",
            "Levenbrech",
            "Fist",
            "High Fist",
            "Imperial Adjunct",
            "Squad Mage",
            "High Mage",
            "Adjutant",
            "Preda",
            "Atri-Preda",
            "Ceda",
            "Atri-Ceda",
            "Septarch",
            "Urdo",
            "Seerdomin",
            "Goa\'uld",
            "First Prime",
            "Field Marshal",
            "Commodore",
            "Fleet Captain",
            "Commander General",
            "Legate",
            "Gu",
            "Glinn",
            "la\'quv",
            "\'aj",
            "Sa\'",
            "totlh",
            "\'ech",
            "Galae",
            "Riov",
            "erei\'Riov",
            "khre\'Arrain",
            "Arrain (Centurion)",
            "erei\'Arrain",
            "Erein",
            "erei\'Erein",
            "khre\'Eredh",
            "Eredh",
            "erei''Eredh",
            "Decurion",
            "Uhlan",
            "Eredh",
            "Farein",
            "DaiMon",
            "Executo",
            "Grand Admiral",
            "Grand General",
            "Moff",
            "High General",
            "Fleet Admiral",
            "Captain of the Line",
            "High Colonel",
            "High Jedi General",
            "Senior Jedi General",
            "Jedi General",
            "Marshal Commander",
            "Senior Commander",
            "Jedi Commander",
            "Regimental Commander",
            "Majo",
            "Lord Commander Militant",
            "Lord General Militant",
            "Colonel-Commissar",
            "Bone\'ead",
            "Chapter Master",
            "Brother-Captain",
            "Brother-Sergeant",
            "Justicar",
            "Battle-Brother",
            "Neophyte",
            "Fleet Admiral",
            "Admiral",
            "Rear Admiral",
            "Captain",
            "Staff Commander",
            "Lieutenant Commander",
            "Staff Lieutenant",
            "1st Lieutenant",
            "2nd Lieutenant",
            "Operations Chief",
            "Gunnery Chief",
            "Service Chief",
            "Serviceman 1st Class",
            "Serviceman 2nd Class",
            "Serviceman 3rd Class",
    };

    private static final String[] LASTNAMES = new String[] {
            "Loray",
            "Thompson",
            "Lipson",
            "Warders",
            "Grison",
            "Reson",
            "Teray",
            "Campbenn",
            "Jamart",
            "Parker",
            "Morgan",
            "Howards",
            "Brownett",
            "Warders",
            "Hughy",
            "Collee",
            "Warder",
            "Bakell",
            "Smaner"
    };
    private static final Random generator = new Random();


    public static String generate() {
        String color = RANKS[generator.nextInt(RANKS.length)];
        String treat = LASTNAMES[generator.nextInt(LASTNAMES.length)];
        return color + " " + treat;
    }
}